### PR TITLE
Windows: persistence eventlog sensor + logon events (#94)

### PR DESCRIPTION
**Pull request by SoFrexs**
﻿## Summary
- Cherry-picks the #94 Windows Event Log persistence/logon-events sensor (`sensor-windows-eventlog`) onto current `main`, reconciled against main's independent schema/ETW-expansion work since this branch diverged.
- Adds `schema::Event::Auth` (logon/session events, normalized from Security 4624/4625/4648/4672) alongside the existing service-install (7045) and scheduled-task (4698) persistence detections -- see ADR-0004 (why wevtutil polling, not EvtSubscribe, for now) and ADR-0005 (shared cross-platform Auth event type).
- Schema bumped 10 -> 11: unions main's independent event-type additions (DnsQuery, RegistrySet, ImageLoad, ScriptBlock, WmiActivity, AssemblyLoad, SmbConnect, UdpSend, SensorHealth) with this branch's Auth event + persistence-artifact flags. Full v11 golden fixture set added.
- `EventLogPolicy` (per-channel-group enable/disable + volume counters) -- ADR-0006.
- Wires a second, supplementary sensor thread in `agent/src/commands/windows.rs`: the eventlog sensor's failure degrades persistence detection but never takes down the ETW sensor.

## Test plan
- [x] `cargo build --release -p agent -p watchdog` -- clean
- [x] `cargo test -p schema -p policy` -- 13/13 policy, 21/21 golden (incl. new auth_logon/auth_logon_failure), 2/2 v1_compat
- [ ] `cargo test -p sensor-windows-eventlog` on this machine (Windows-only cfg)
- [ ] Manual: wevtutil-based validation on a real Windows VM for logon events specifically (persistence detections already lab-validated per ADR-0004; logon-event field parsing is new and flagged as unreconciled in the crate doc)

### CODE REVIEW

**Comment by old-dov** [comment]
Reviewed #188 (compiled `agent`/`watchdog` + `schema`/`policy` tests locally — matches the PR's own results).

**Confirmed compile break on `main` once merged: `sensor-linux` (Linux userspace sensor) will not build.**

`crates/schema/src/sensor.rs` gains `pub auth_events: bool` on `Capabilities`. That struct derives `Default`, but `crates/sensors/linux/userspace/src/sensor.rs:474` constructs it as an exhaustive literal (no `..Default::default()`):

```rust
fn capabilities(&self) -> Capabilities {
    Capabilities {
        exec_events: true,
        file_events: true,
        connect_events: true,
        user_attribution: true,
        parent_lineage: true,
    }
}
```

Checked out this branch and ran it for real (WSL, `edr-lab`):

```
error[E0063]: missing field `auth_events` in initializer of `Capabilities`
   --> crates/sensors/linux/userspace/src/sensor.rs:474:9
```

Full workspace check (excluding Windows-only crates and `ml`, which has its own unrelated `openssl-sys`/pkg-config gap) shows this is the *only* break — nothing else references `Capabilities` as an exhaustive literal. Fix is a one-line add (`auth_events: false,` — the Linux sensor doesn't emit `Event::Auth` either) to that literal before this merges.

**Relationship to #184:** that PR is now redundant/subsumed — it only adds the `auth_events: false,` line on the *Windows* ETW sensor side and doesn't touch `schema/src/sensor.rs` at all, which is why it doesn't compile on its own (the field doesn't exist yet on `main`). This PR already does both halves of #184's fix (struct field + ETW sensor value) plus the eventlog sensor's own value. Once #188 lands, #184 should just be closed rather than merged separately — merging both would conflict on the same lines. Worth telling Hugo before he spends time on #184 tomorrow; the actual missing piece was the Linux sensor literal, not a Linux-side feature gap.

Rest of the PR (Auth event type, ADR-0004/0005/0006, eventlog sensor, v11 fixtures) not reviewed in depth yet — flagging this one because it blocks `main` for everyone else, not just Windows.

**Comment by Sollykhan** [comment]
Pushed the one-line fix @old-dov flagged in the review — added `auth_events: false,` to the exhaustive `Capabilities` literal in `crates/sensors/linux/userspace/src/sensor.rs` (Linux sensor doesn't emit `Event::Auth`, so `false` is correct).

Pushed directly on the branch with @sofrexs's Discord go-ahead — he's on a test run and can't commit right now, we didn't want to hold main hostage another day given the demo deadline.

Verified: `cargo check -p sensor-linux` clean locally on WSL. Rest of the PR (Auth event type, ADR-0004/0005/0006, eventlog sensor, v11 fixtures) untouched — @old-dov, ready for the deeper review pass whenever you have a moment.

Also flagging for follow-up: #184 should be closed (subsumed by this PR per @old-dov's review), and #185 has a test hardcoded path Windows-side to fix (`env::temp_dir().join(...)` pattern) — both signaled to @sofrexs on Discord yesterday.

**Comment by old-dov** [comment]
Rebased on `main` to resolve the merge conflict (this branch predated #189/#193's schema work).

- `SCHEMA_VERSION`: this branch's original 10 → 11 claim collided with #189's now-merged 11 → 12 (`NetworkFlow`) — same coordination note already flagged in an earlier session. Rebased to **12 → 13**.
- `tests/fixtures/v13/` replaces this branch's `v11/`: a full fresh snapshot of `v12/` (includes `listen_port`/`network_flow`, already on `main`) plus the two new `auth_logon`/`auth_logon_failure` fixtures — same "full snapshot per bump" convention ADR-0005 already established.
- `Event` enum / `meta()` match: merged cleanly (`Auth` alongside `ListenPort`/`NetworkFlow`, no semantic overlap).

Verified natively on Windows after the rebase: `schema` golden suite (23/23, including both new `auth_logon*` fixtures), full `agent`/`schema`/`policy`/`enrich`/`sensor-windows`/`sensor-windows-eventlog`/`rules`/`correlator` build + test + clippy `-D warnings` — all green. `gh pr view` now reports `MERGEABLE`/`CLEAN`.
